# Generated by Django 4.1.3 on 2022-11-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdetItem',
            new_name='OrdertItem',
        ),
    ]
