# Generated by Django 4.1.3 on 2022-11-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('orders', '0002_rename_ordetitem_ordertitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdertItem',
            new_name='OrderItem',
        ),
    ]
